fix: calculation of nb_dimensions for approximated inverse
octopize/saiph pull request #137
Opened 2024-09-24 08:25 UTC by tas17

2024-09-24 09:12 UTC, jpetot requested changes

2024-09-24 09:12 UTC, jpetot commented on saiph/inverse_transform.py
> +    n_dimensions = len(model.dummy_categorical) + len(model.original_continuous) - 1
```suggestion
    n_dimensions = len(model.dummy_categorical) + len(model.original_continuous) - nb_variable_categorical 
```

2024-09-24 09:12 UTC, jpetot commented on saiph/inverse_transform.py
> +    n_dimensions = len(model.dummy_categorical) + len(model.original_continuous) - 1
could you create unit test of this fix?

2024-09-24 16:11 UTC, tas17 commented on saiph/inverse_transform.py
> +    )
Note: I was first using `model: Model` as the only input, but as it's a `@DataClass`, I could not generate a factory for it.
So I went to use that workaround instead

2024-09-25 07:09 UTC, jpetot requested changes
Sorry if I wasn't clear enough for this point

2024-09-25 07:09 UTC, jpetot commented on saiph/models.py
> +    return len(dummy_categorical) + len(original_continuous) - 1
```suggestion
    return len(dummy_categorical) + len(original_continuous) - nb_categorical_variable
```

2024-09-25 07:28 UTC, closed without merging